name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Bot"
          git checkout --orphan hf_deploy
          git add -A
          git commit -m "Deploy to Hugging Face"
          git push --force https://Dyanneey:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Dyanneey/backend-koperasi hf_deploy:main
